from pathlib import Path
from typing import Any

import httpx
from fastapi import APIRouter, HTTPException

from app.core.constants import REMOTE_TOKEN


router = APIRouter()


BASE_API = "http://117.149.9.79:9003"

AUTH_URL = f"{BASE_API}/auth/token"
AUTH_HEADERS = {
    "accept": "application/json",
    "Content-Type": "application/x-www-form-urlencoded",
}
AUTH_FORM = {
    "username": "xcxjk",
    "password": "aoruixcx123..",
    "scope": "",
}


def _constants_path() -> Path:
    # Constants file where the token will be written
    return Path(__file__).resolve().parents[2] / "core" / "constants.py"


def _write_token_to_constants(token: str, raw: dict[str, Any] | None = None) -> None:
    p = _constants_path()
    p.parent.mkdir(parents=True, exist_ok=True)
    # Minimal constants file with a single token constant. Also stores raw JSON for debugging.
    content_lines = [
        "# Auto-generated by /api/token endpoint. Do not edit manually.",
        f"REMOTE_TOKEN = {token!r}",
    ]
    if raw is not None:
        # Best-effort raw data for later inspection (not required to be imported elsewhere)
        content_lines.append(f"REMOTE_TOKEN_RAW = {raw!r}")
    p.write_text("\n".join(content_lines) + "\n", encoding="utf-8")


async def _fetch_token() -> dict:
    async with httpx.AsyncClient(timeout=15.0) as client:
        resp = await client.post(AUTH_URL, headers=AUTH_HEADERS, data=AUTH_FORM)
        resp.raise_for_status()
        return resp.json()


def _extract_token(data: dict[str, Any]) -> str | None:
    # Try a few common keys
    for key in ("access_token", "token", "id_token"):
        val = data.get(key)
        print('>>>>val', val);
        if isinstance(val, str) and val:
            return val
    return None


@router.get("/token")
@router.post("/token")
async def get_remote_token():
    try:
        data = await _fetch_token()
        print('>>>>data', data);
    except httpx.HTTPError as e:
        raise HTTPException(status_code=502, detail=f"Auth service error: {e}")

    token = _extract_token(data)
    if not token:
        # Still write raw data for visibility
        _write_token_to_constants("", raw=data)
        raise HTTPException(status_code=500, detail="Token not found in auth response")

    _write_token_to_constants(token, raw=data)
    return {"success": True, "token": token, "code": 200}


async def _fetch_projects() -> dict:
    async with httpx.AsyncClient(timeout=15.0) as client:
        headers = {
            "accept": "application/json",
            "Content-Type": "application/json",
            "Authorization": f"Bearer {REMOTE_TOKEN}"
        }
        payload = {
            "pagesize": None,
            "pagenumber": 1,
            "query": {}
        }
        resp = await client.post(f"{BASE_API}/api/p/list", headers=headers, json=payload)
        resp.raise_for_status()
        return resp.json()

# get请求获取projects，api是 /api/p/list
@router.get("/projects")
async def get_projects():
    projects = await _fetch_projects()
    return projects