from pathlib import Path
import asyncio
import base64
import importlib
import sys
from datetime import datetime, date
from typing import Any
from urllib.parse import quote

from fastapi.responses import JSONResponse, StreamingResponse
import httpx
from fastapi import APIRouter, HTTPException, Depends, Query, Response
from sqlalchemy import text
from common.decorators import log_exceptions
from sqlalchemy.orm import Session
from api.deps import get_db, get_db_lims
from models.sample import Sample
from models import User
from crud import sample as crud_sample
from schemas.sample import SampleCreate
from crud import user as crud_user
from schemas.user import UserCreate
from settings import BASE_API

try:
    from core.constants import REMOTE_TOKEN
except Exception:
    REMOTE_TOKEN = ""


router = APIRouter()


# TODO：正式环境
# BASE_API = "http://10.110.1.22:9003"
# TODO：开发环境
# BASE_API = "http://117.149.9.79:9003"

AUTH_URL = f"{BASE_API}/auth/token"
AUTH_HEADERS = {
    "accept": "application/json",
    "Content-Type": "application/x-www-form-urlencoded",
}
AUTH_FORM = {
    "username": "xcxjk",
    "password": "aoruixcx123..",
    "scope": "",
}


def _constants_path() -> Path:
    # Constants file where the token will be written
    return Path(__file__).resolve().parents[2] / "core" / "constants.py"


def _write_token_to_constants(token: str, raw: dict[str, Any] | None = None) -> None:
    p = _constants_path()
    p.parent.mkdir(parents=True, exist_ok=True)
    # Minimal constants file with a single token constant. Also stores raw JSON for debugging.
    content_lines = [
        "# Auto-generated by /api/token endpoint. Do not edit manually.",
        f"REMOTE_TOKEN = {token!r}",
    ]
    if raw is not None:
        # Best-effort raw data for later inspection (not required to be imported elsewhere)
        content_lines.append(f"REMOTE_TOKEN_RAW = {raw!r}")
    p.write_text("\n".join(content_lines) + "\n", encoding="utf-8")


async def _fetch_token() -> dict:
    async with httpx.AsyncClient(timeout=15.0) as client:
        resp = await client.post(AUTH_URL, headers=AUTH_HEADERS, data=AUTH_FORM)
        resp.raise_for_status()
        return resp.json()


def _extract_token(data: dict[str, Any]) -> str | None:
    # Try a few common keys
    for key in ("access_token", "token", "id_token"):
        val = data.get(key)
        print('>>>>val', val);
        if isinstance(val, str) and val:
            return val
    return None


async def _refresh_token_and_reload() -> str | None:
    """刷新 token 并重新加载模块以更新全局 REMOTE_TOKEN"""
    global REMOTE_TOKEN
    try:
        data = await _fetch_token()
        token = _extract_token(data)
        if not token:
            print('>>>>refresh_token: Token not found in auth response')
            return None
        _write_token_to_constants(token, raw=data)
        # 重新加载 core.constants 模块以更新 REMOTE_TOKEN
        if 'core.constants' in sys.modules:
            importlib.reload(sys.modules['core.constants'])
            from core.constants import REMOTE_TOKEN as NEW_TOKEN
            REMOTE_TOKEN = NEW_TOKEN
        else:
            from core.constants import REMOTE_TOKEN as NEW_TOKEN
            REMOTE_TOKEN = NEW_TOKEN
        print('>>>>refresh_token: Token refreshed successfully')
        return token
    except Exception as e:
        print(f'>>>>refresh_token failed: {repr(e)}')
        return None


async def _make_request_with_retry(request_func):
    """执行 HTTP 请求，如果遇到 401 错误则自动刷新 token 并重试一次"""
    try:
        return await request_func()
    except httpx.HTTPStatusError as e:
        if e.response.status_code == 401:
            print('>>>>401 Unauthorized detected, refreshing token...')
            new_token = await _refresh_token_and_reload()
            if new_token:
                print('>>>>Token refreshed, retrying request...')
                # 重试一次
                return await request_func()
            else:
                print('>>>>Failed to refresh token, raising original error')
                raise
        else:
            raise


@router.get("/token")
@router.post("/token")
@log_exceptions
async def get_remote_token():
    try:
        data = await _fetch_token()
        print('>>>>data', data);
    except httpx.HTTPError as e:
        raise HTTPException(status_code=502, detail=f"Auth service error: {e}")

    token = _extract_token(data)
    if not token:
        # Still write raw data for visibility
        _write_token_to_constants("", raw=data)
        raise HTTPException(status_code=500, detail="Token not found in auth response")

    _write_token_to_constants(token, raw=data)
    return {"success": True, "token": token, "code": 200}


async def _fetch_projects() -> dict:
    async def _do_request():
        async with httpx.AsyncClient(timeout=15.0) as client:
            headers = {
                "accept": "application/json",
                "Content-Type": "application/json",
                "Authorization": f"Bearer {REMOTE_TOKEN}"
            }
            payload = {
                "pagesize": None,
                "pagenumber": 1,
                "query": {}
            }
            resp = await client.post(f"{BASE_API}/api/p/list", headers=headers, json=payload)
            resp.raise_for_status()
            return resp.json()
    return await _make_request_with_retry(_do_request)

async def _fetch_pdf_list(order_id: int | str) -> list[dict]:
    async def _do_request():
        async with httpx.AsyncClient(timeout=20.0) as client:
            headers = {
                "accept": "application/json",
                "Content-Type": "application/json",
                "Authorization": f"Bearer {REMOTE_TOKEN}",
            }
            url = f"{BASE_API}/api/pdf/list?pk={order_id}"
            resp = await client.post(url, headers=headers)
            print('>>>>pdf_list_resp_status', resp.status_code)
            resp.raise_for_status()
            data = resp.json()
            print('>>>>pdf_list_resp_body', data.get('status_code'), data.get('message'))
            content = data.get('content')
            return content if isinstance(content, list) else []
    return await _make_request_with_retry(_do_request)

async def _download_pdf_file(pk: int | str) -> httpx.Response:
    async def _do_request():
        async with httpx.AsyncClient(timeout=None, follow_redirects=True) as client:
            headers = {
                "accept": "application/pdf,application/octet-stream,*/*",
                "Authorization": f"Bearer {REMOTE_TOKEN}",
            }
            url = f"{BASE_API}/api/pdf/download?pk={pk}"
            # Stream the response to avoid buffering and preserve binary integrity
            resp = await client.post(url, headers=headers)
            return resp
    return await _make_request_with_retry(_do_request)


async def _download_binary_stream(pk: int | str):
    """下载二进制数据流（PDF）并流式返回"""
    try:
        async with httpx.AsyncClient(timeout=None, follow_redirects=True) as client:
            headers = {
                "accept": "application/pdf,application/octet-stream,*/*",
                "Authorization": f"Bearer {REMOTE_TOKEN}",
            }
            url = f"{BASE_API}/api/pdf/download/wx?pk={pk}"
            async with client.stream("POST", url, headers=headers) as resp:
                resp.raise_for_status()
                # 流式读取二进制数据
                async for chunk in resp.aiter_bytes():
                    yield chunk
    except httpx.HTTPStatusError as e:
        if e.response.status_code == 401:
            print('>>>>401 Unauthorized detected in stream, refreshing token...')
            new_token = await _refresh_token_and_reload()
            if new_token:
                print('>>>>Token refreshed, retrying stream request...')
                # 重试一次
                async with httpx.AsyncClient(timeout=None, follow_redirects=True) as client:
                    headers = {
                        "accept": "application/pdf,application/octet-stream,*/*",
                        "Authorization": f"Bearer {REMOTE_TOKEN}",
                    }
                    url = f"{BASE_API}/api/pdf/download?pk={pk}"
                    async with client.stream("POST", url, headers=headers) as resp:
                        resp.raise_for_status()
                        # 流式读取二进制数据
                        async for chunk in resp.aiter_bytes():
                            yield chunk
            else:
                print('>>>>Failed to refresh token, raising original error')
                raise
        else:
            raise

def _serialize_datetime(obj: Any) -> Any:
    """递归地将字典中的 datetime 和 date 对象转换为字符串"""
    if isinstance(obj, datetime):
        return obj.isoformat()
    elif isinstance(obj, date):
        return obj.isoformat()
    elif isinstance(obj, dict):
        return {key: _serialize_datetime(value) for key, value in obj.items()}
    elif isinstance(obj, list):
        return [_serialize_datetime(item) for item in obj]
    else:
        return obj


def _get_projects_data(db: Session):
    """获取项目数据的核心逻辑，可被其他模块调用"""
    sql = text("select * from program where usable = 1")
    result = db.execute(sql)
    # 使用 mappings() 将 Row 对象转换为字典，然后转换为普通字典列表以便 JSON 序列化
    rows = result.mappings().all()
    # 将 RowMapping 对象转换为普通字典，并将 id 字段转换为字符串
    projects = []
    for row in rows:
        project_dict = dict(row)
        if 'id' in project_dict and project_dict['id'] is not None:
            project_dict['id'] = str(project_dict['id'])
        projects.append(project_dict)
    # 递归处理 datetime 对象
    return _serialize_datetime(projects)


# get请求获取projects，api是 /api/p/list
@router.get("/projects")
@log_exceptions
async def get_projects(db: Session = Depends(get_db_lims)):
    projects = _get_projects_data(db)
    print('>>>>projects', projects)
    return JSONResponse(
        content={"message": "success", "data": projects},
        status_code=200,
    )
    # projects = await _fetch_projects()
    # data = projects.get('content').get('rows');
    # print('>>>>projects', );
    # return JSONResponse(
    #     content={"message": "success", "data": {"list": data, "total": 100}},
    #     status_code=200,
    # )


async def _post_remote_api(payload: dict) -> dict:
    async def _do_request():
        async with httpx.AsyncClient(timeout=20.0) as client:
            headers = {
                "accept": "application/json",
                "Content-Type": "application/json",
                "Authorization": f"Bearer {REMOTE_TOKEN}",
            }
            resp = await client.post(f"{BASE_API}/api", headers=headers, json=payload)
            print('>>>>resp', resp.json().get('content'))
            resp.raise_for_status()
            return resp.json().get('content')
    return await _make_request_with_retry(_do_request)


# def _extract_remote_id(data: dict[str, Any]) -> Any:
    # Try common locations for an identifier
    # return data.get('id');
    # for key in ("id", "order_id"):
    #     if key in data:
    #         return data[key]
    # content = data.get("content") if isinstance(data, dict) else None
    # if isinstance(content, dict):
    #     for key in ("id", "order_id"):
    #         if key in content:
    #             return content[key]
    # return None


@router.post("/sample/create")
@log_exceptions
async def create_remote_order(payload: dict, db: Session = Depends(get_db)):
    samples = payload.get("samples") if isinstance(payload, dict) else None
    first = samples[0] if isinstance(samples, list) and samples and isinstance(samples[0], dict) else None
    print('>>>>first', first);
    # 1) Map payload -> local Sample fields
    customer = payload.get("customer") if isinstance(payload, dict) else None
    code = (first or {}).get("other_code")
    name = (customer or {}).get("name")
    gender = (customer or {}).get("gender")  # male/female
    age = (customer or {}).get("age")
    phone = (customer or {}).get("phone")
    id_number = (customer or {}).get("id_number")
    programs = (first or {}).get("programs") or []
    program_id = int(programs[0]) if programs else 0
    try:
        org_id = int(payload.get("org_id")) if payload.get("org_id") is not None else 0
    except Exception:
        org_id = 0
    desc = (first or {}).get("remarks")
    user_id = (customer or {}).get("user_id")
    # 2) TODO: Ensure user exists (by phone), else create a minimal user 
    # user_obj = None
    # if phone:
    #     user_obj = db.query(User).filter(User.phone == phone).first()
    # if not user_obj:
    #     # Create a basic user to satisfy Sample.user_id FK-like link
    #     uc = UserCreate(name=(customer or {}).get("name"), avatar="", phone=phone, id_number=id_number, sex=sex, age=None)  # type: ignore[arg-type]
    #     user_obj = crud_user.create_user(db, user=uc)

    # 3) Create or reuse local Sample by code
    db_sample = None
    print('>>>>code', code);
    if code:
        db_sample = db.query(Sample).filter(Sample.code == code).first()
        print('>>>>code', code, '>', name, '>', user_id, '>', phone, '>', id_number, '>', gender, '>', age, '>', program_id, '>', org_id, '>', desc);
    if not db_sample:
        sc = SampleCreate(
            code=code or "",
            name=name,
            type="fullBlood",
            process="progressing",
            user_id=user_id,
            phone=phone,
            id_number=id_number,
            gender=gender,
            age=age,
            program_id=str(program_id),
            org_id=str(org_id),
            sample_data_id=None,
            order_id=None,
            desc=desc or "",
        )
        print('>>>>sc', sc);
        db_sample = crud_sample.create_sample(db, sample=sc)
    print('>>>>db_sample', db_sample);
    # 4) Forward to remote API
    remote_resp = await _post_remote_api(payload)

    # 5) Update local sample.order_id from remote response
    # Prefer explicit order id fields from remote, fallback only if necessary.
    remote_code = None
    try:
        remote_code_list = remote_resp.get("other_code_list")
        if isinstance(remote_code_list, list) and remote_code_list:
            remote_code = remote_code_list[0]
    except Exception:
        remote_code = None

    # Extract potential order id from common keys
    order_id_val = remote_resp.get('id')

    print('>>>>remote_code/order_id_src', remote_code, order_id_val, remote_resp)
    try:
        if db_sample:
            if remote_code and db_sample.code != remote_code:
                # In case remote assigned/echoed a different code, try match and update that row
                target = db.query(Sample).filter(Sample.code == remote_code).first()
            else:
                target = db_sample
            print('>>>>target before update', target, order_id_val)
            if target is not None and order_id_val is not None:
                try:
                    target.order_id = str(order_id_val)
                except Exception as _:
                    target.order_id = None
                db.commit()
                db.refresh(target)
                print('>>>>target after update', target.order_id)
    except Exception as e:
        # Avoid failing the endpoint if update fails
        print('>>>>update sample.order_id failed:', repr(e))

    # 6) With order_id, fetch pdf list and update sample_data_id by barcode (simple retry)
    max_retries = 3
    delay_seconds = 2
    try:
        if order_id_val is not None:
            for attempt in range(1, max_retries + 1):
                try:
                    pdf_items = await _fetch_pdf_list(order_id_val)
                except Exception as fetch_err:
                    print(f'>>>>pdf_list fetch error attempt {attempt}:', repr(fetch_err))
                    pdf_items = []

                print('>>>>pdf_items_len', len(pdf_items) if isinstance(pdf_items, list) else None, 'attempt', attempt)
                updated_any = False
                if isinstance(pdf_items, list) and pdf_items:
                    for item in pdf_items:
                        try:
                            barcode = (item or {}).get('barcode')
                            sample_data_id = (item or {}).get('sample_data_id')
                            if not barcode or sample_data_id is None:
                                continue
                            target = db.query(Sample).filter(Sample.code == barcode).first()
                            if not target:
                                continue
                            try:
                                target.sample_data_id = str(sample_data_id)
                            except Exception:
                                target.sample_data_id = None
                            # also persist the pdf item name into sample_data_name
                            sample_data_name = (item or {}).get('name')
                            if isinstance(sample_data_name, str) and sample_data_name:
                                target.sample_data_name = sample_data_name
                            db.commit()
                            db.refresh(target)
                            updated_any = True
                            print('>>>>updated sample_data_id/name', barcode, target.sample_data_id, target.sample_data_name)
                        except Exception as _:
                            # continue on item-level errors
                            continue

                if updated_any:
                    break
                if attempt < max_retries:
                    await asyncio.sleep(delay_seconds)
            else:
                print('>>>>pdf list retry exhausted without updates')
    except Exception as e:
        print('>>>>fetch/update pdf list failed:', repr(e))

    return JSONResponse(
        content={
            "message": "success",
            "data": remote_resp,
        },
        status_code=200,
    )


@router.get("/report/pdf")
@log_exceptions
async def get_report_pdf(pk: str = Query(..., description="sample_data_id from remote")):
    """接收外部接口的二进制数据流（PDF），同时返回二进制数据流"""
    try:
        # 设置中文文件名，使用 RFC 5987 格式支持中文
        # 注意：HTTP 头必须使用 latin-1 编码，所以使用 filename* 参数
        filename = "样本.pdf"
        # URL 编码文件名（UTF-8），quote 默认使用 UTF-8 编码
        encoded_filename = quote(filename)
        # 只使用 filename* 参数，避免 latin-1 编码问题
        content_disposition = f'attachment; filename*=UTF-8\'\'{encoded_filename}'
        
        # 流式传输二进制数据（PDF）
        return StreamingResponse(
            _download_binary_stream(pk),
            media_type="application/pdf",
            headers={
                "Content-Type": "application/pdf",
                "Content-Disposition": content_disposition,
            }
        )
    except httpx.HTTPStatusError as e:
        raise HTTPException(status_code=e.response.status_code, detail=f"Remote API error: {e}")
    except httpx.RequestError as e:
        raise HTTPException(status_code=502, detail=f"Failed to connect to remote API: {e}")


@router.get("/report/pdf/download")
@router.post("/report/pdf/download")
@log_exceptions
async def download_pdf_to_local(pk: str = Query(..., description="sample_data_id from remote")):
    """下载远程 PDF 文件到本地 static 目录，使用 pk 作为文件名"""
    try:
        # 确定 static 目录路径（相对于 remote.py 文件：app/api/routes/remote.py -> 项目根目录/static）
        static_dir = Path(__file__).resolve().parents[3] / "app/static"
        static_dir.mkdir(parents=True, exist_ok=True)
        
        # 使用 pk 作为文件名，添加 .pdf 扩展名
        file_path = static_dir / f"{pk}.pdf"
        
        # 如果文件已存在，可以选择跳过或覆盖（这里选择覆盖）
        print(f'>>>>downloading PDF to: {file_path}')
        
        # 下载 PDF 数据
        pdf_data = b""
        async for chunk in _download_binary_stream(pk):
            pdf_data += chunk
        
        if not pdf_data:
            raise HTTPException(status_code=404, detail="PDF file is empty or not found")
        
        # 保存到本地文件
        file_path.write_bytes(pdf_data)
        
        print(f'>>>>PDF saved successfully: {file_path}, size: {len(pdf_data)} bytes')
        
        return JSONResponse(
            content={
                "message": "success",
                "data": {
                    "pk": pk,
                    "file_path": str(file_path),
                    "file_name": f"{pk}.pdf",
                    "size": len(pdf_data),
                },
            },
            status_code=200,
        )
    except httpx.HTTPStatusError as e:
        error_detail = f"Remote API error: {e}"
        print(f'>>>>download_pdf_to_local HTTPStatusError: {error_detail}')
        raise HTTPException(status_code=e.response.status_code if e.response else 500, detail=error_detail)
    except httpx.RequestError as e:
        print(f'>>>>download_pdf_to_local RequestError: {e}')
        raise HTTPException(status_code=502, detail=f"Failed to connect to remote API: {e}")
    except Exception as e:
        print(f'>>>>download_pdf_to_local Exception: {repr(e)}')
        raise HTTPException(status_code=500, detail=f"Failed to save PDF file: {e}")


@router.get("/report/pdf/local")
@log_exceptions
async def get_local_pdf(pk: str = Query(..., description="sample_data_id from remote")):
    """读取本地static目录下的PDF文件并返回，如果不存在则先从远程下载"""
    try:
        # 确定 static 目录路径
        static_dir = Path(__file__).resolve().parents[3] / "app/static"
        file_path = static_dir / f"{pk}.pdf"
        
        # 检查文件是否存在，如果不存在则先下载
        if not file_path.exists():
            # 调用内部的下载函数下载PDF文件
            await download_pdf_to_local(pk=pk)
            
            # 再次检查文件是否成功下载
            if not file_path.exists():
                raise HTTPException(status_code=500, detail=f"Failed to download PDF file {pk}.pdf")
        
        # 检查是否为文件（而非目录）
        if not file_path.is_file():
            raise HTTPException(status_code=400, detail=f"{pk}.pdf is not a valid file")
        
        # 设置中文文件名，使用 RFC 5987 格式支持中文
        filename = "样本.pdf"
        encoded_filename = quote(filename)
        # 使用 inline 使PDF在浏览器中直接打开而不是下载
        content_disposition = f'inline; filename*=UTF-8\'\'{encoded_filename}'
        
        # 返回文件内容
        def iterfile():
            with open(file_path, mode="rb") as file_like:
                yield from file_like
                
        return StreamingResponse(
            iterfile(),
            media_type="application/pdf",
            headers={
                "Content-Disposition": content_disposition,
            }
        )
    except HTTPException:
        raise
    except Exception as e:
        print(f'>>>>get_local_pdf Exception: {repr(e)}')
        raise HTTPException(status_code=500, detail=f"Failed to read PDF file: {e}")


@router.post("/static/clear")
@log_exceptions
async def clear_static_files():
    """清除 static 目录下的所有文件"""
    try:
        # 确定 static 目录路径
        static_dir = Path(__file__).resolve().parents[3] / "app/static"
        
        # 确保目录存在
        if not static_dir.exists():
            return JSONResponse(
                content={
                    "message": "success",
                    "data": {
                        "deleted_count": 0,
                        "message": "Static directory does not exist",
                    },
                },
                status_code=200,
            )
        
        # 统计删除的文件数量
        deleted_count = 0
        deleted_files = []
        
        # 遍历目录中的所有文件并删除
        for file_path in static_dir.iterdir():
            if file_path.is_file():
                try:
                    file_path.unlink()
                    deleted_count += 1
                    deleted_files.append(file_path.name)
                    print(f'>>>>Deleted file: {file_path.name}')
                except Exception as e:
                    print(f'>>>>Failed to delete file {file_path.name}: {repr(e)}')
        
        print(f'>>>>Cleared static directory: {deleted_count} files deleted')
        
        return JSONResponse(
            content={
                "message": "success",
                "data": {
                    "deleted_count": deleted_count,
                    "deleted_files": deleted_files,
                },
            },
            status_code=200,
        )
    except Exception as e:
        print(f'>>>>clear_static_files Exception: {repr(e)}')
        raise HTTPException(status_code=500, detail=f"Failed to clear static files: {e}")



async def _get_mongo_mongoid(payload: dict) -> dict:
    async def _do_request():
        async with httpx.AsyncClient(timeout=20.0) as client:
            headers = {
                "accept": "application/json",
                "Authorization": f"Bearer {REMOTE_TOKEN}",
            }
            resp = await client.get(f"{BASE_API}/api/mongo/{payload.get('mongoid')}", headers=headers)
            print('>>>>resp', resp.json().get('content'))
            resp.raise_for_status()
            return resp.json().get('content')
    return await _make_request_with_retry(_do_request)


@router.get("/mongoInfo")
@log_exceptions
async def get_mongo_info(mongoid: str = Query(..., description="MongoDB document ID")):
    """根据 mongoid 获取 MongoDB 信息"""
    try:
        payload = {"mongoid": mongoid}
        result = await _get_mongo_mongoid(payload)
        return JSONResponse(
            content={
                "message": "success",
                "data": result,
            },
            status_code=200,
        )
    except httpx.HTTPStatusError as e:
        raise HTTPException(status_code=e.response.status_code, detail=f"Remote API error: {e}")
    except httpx.RequestError as e:
        raise HTTPException(status_code=502, detail=f"Failed to connect to remote API: {e}")