from pathlib import Path
from typing import Any

from fastapi.responses import JSONResponse
import httpx
from fastapi import APIRouter, HTTPException, Depends
from app.common.decorators import log_exceptions
from sqlalchemy.orm import Session
from app.api.deps import get_db
from app.models.sample import Sample

try:
    from app.core.constants import REMOTE_TOKEN
except Exception:
    REMOTE_TOKEN = ""


router = APIRouter()


BASE_API = "http://117.149.9.79:9003"

AUTH_URL = f"{BASE_API}/auth/token"
AUTH_HEADERS = {
    "accept": "application/json",
    "Content-Type": "application/x-www-form-urlencoded",
}
AUTH_FORM = {
    "username": "xcxjk",
    "password": "aoruixcx123..",
    "scope": "",
}


def _constants_path() -> Path:
    # Constants file where the token will be written
    return Path(__file__).resolve().parents[2] / "core" / "constants.py"


def _write_token_to_constants(token: str, raw: dict[str, Any] | None = None) -> None:
    p = _constants_path()
    p.parent.mkdir(parents=True, exist_ok=True)
    # Minimal constants file with a single token constant. Also stores raw JSON for debugging.
    content_lines = [
        "# Auto-generated by /api/token endpoint. Do not edit manually.",
        f"REMOTE_TOKEN = {token!r}",
    ]
    if raw is not None:
        # Best-effort raw data for later inspection (not required to be imported elsewhere)
        content_lines.append(f"REMOTE_TOKEN_RAW = {raw!r}")
    p.write_text("\n".join(content_lines) + "\n", encoding="utf-8")


async def _fetch_token() -> dict:
    async with httpx.AsyncClient(timeout=15.0) as client:
        resp = await client.post(AUTH_URL, headers=AUTH_HEADERS, data=AUTH_FORM)
        resp.raise_for_status()
        return resp.json()


def _extract_token(data: dict[str, Any]) -> str | None:
    # Try a few common keys
    for key in ("access_token", "token", "id_token"):
        val = data.get(key)
        print('>>>>val', val);
        if isinstance(val, str) and val:
            return val
    return None


@router.get("/token")
@router.post("/token")
@log_exceptions
async def get_remote_token():
    try:
        data = await _fetch_token()
        print('>>>>data', data);
    except httpx.HTTPError as e:
        raise HTTPException(status_code=502, detail=f"Auth service error: {e}")

    token = _extract_token(data)
    if not token:
        # Still write raw data for visibility
        _write_token_to_constants("", raw=data)
        raise HTTPException(status_code=500, detail="Token not found in auth response")

    _write_token_to_constants(token, raw=data)
    return {"success": True, "token": token, "code": 200}


async def _fetch_projects() -> dict:
    async with httpx.AsyncClient(timeout=15.0) as client:
        headers = {
            "accept": "application/json",
            "Content-Type": "application/json",
            "Authorization": f"Bearer {REMOTE_TOKEN}"
        }
        payload = {
            "pagesize": None,
            "pagenumber": 1,
            "query": {}
        }
        resp = await client.post(f"{BASE_API}/api/p/list", headers=headers, json=payload)
        resp.raise_for_status()
        return resp.json()

# get请求获取projects，api是 /api/p/list
@router.get("/projects")
@log_exceptions
async def get_projects():
    projects = await _fetch_projects()
    data = projects.get('content').get('rows');
    print('>>>>projects', );
    return JSONResponse(
        content={"message": "success", "data": {"list": data, "total": 100}},
        status_code=200,
    )


async def _post_remote_api(payload: dict) -> dict:
    async with httpx.AsyncClient(timeout=20.0) as client:
        headers = {
            "accept": "application/json",
            "Content-Type": "application/json",
            "Authorization": f"Bearer {REMOTE_TOKEN}",
        }
        resp = await client.post(f"{BASE_API}/api", headers=headers, json=payload)
        print('>>>>resp', resp.json());
        resp.raise_for_status()
        return resp.json()


def _extract_remote_id(data: dict[str, Any]) -> Any:
    # Try common locations for an identifier
    # # for key in ("id", "order_id"):
    # #     if key in data:
    # #         return data[key]
    content = data.get("content") if isinstance(data, dict) else None
    if isinstance(content, dict):
        for key in ("id", "order_id"):
            if key in content:
                return content[key]
    return None


@router.post("/sample/create")
@log_exceptions
async def create_remote_order(payload: dict, db: Session = Depends(get_db)):
    # Forward to remote API
    remote_resp = await _post_remote_api(payload)

    # Extract id from remote response
    remote_id = _extract_remote_id(remote_resp)
    print('>>>>remote_id', remote_id, payload);
    # Try to map back to local sample via provided samples[0].other_code (fallback to code)
    updated_sample_id: int | None = None
    try:
        samples = payload.get("samples") if isinstance(payload, dict) else None
        if isinstance(samples, list) and samples:
            first = samples[0] if isinstance(samples[0], dict) else None
            print('>>>>first', first);
            if first:
                local_code = first.get("other_code") or first.get("code")
                if local_code:
                    db_sample = db.query(Sample).filter(Sample.code == local_code).first()
                    if db_sample and remote_id is not None:
                        try:
                            db_sample.order_id = int(remote_id)
                        except Exception:
                            # keep as None if not castable
                            db_sample.order_id = None
                        db.commit()
                        db.refresh(db_sample)
                        updated_sample_id = db_sample.sample_id
    except Exception:
        # Swallow mapping errors; still return remote response
        pass

    return JSONResponse(
        content={
            "message": "success",
            "data": {"remote": remote_resp, "order_id": remote_id, "updated_sample_id": updated_sample_id},
        },
        status_code=200,
    )
